[project]
name = "python-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "returns>=0.29.0",
    "streamlit>=1.60.0",
    "structlog>=26.1.0",
    "dataframe-lib",
    "starlette<0.48",
    "matplotlib>=3.11.1",
]

[tool.uv.sources]
dataframe-lib = {
    path = "lib",
    editable = true,
}